name: echocall
description: "This Flutter app meticulously logs incoming and outgoing calls, capturing essential details like caller ID, duration, timestamp, and originating SIM, then seamlessly uploads this rich call data to Firebase for comprehensive tracking and analysis."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  android_intent_plus: ^6.0.0
  disable_battery_optimization: ^1.1.2
  intl: 0.20.2
  cloud_firestore: '>=5.5.0'
  firebase_core: '>=2.21.1'
  shared_preferences: ^2.0.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications:
  phone_state: ^2.0.0
  call_log: ^6.0.0
  permission_handler: ^12.0.0
  pdf: ^3.0.0
  excel: ^4.0.0
  path_provider: ^2.0.0
  share_plus: ^10.0.2
  provider: ^6.0.0
  sim_data:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
